# http://travis-ci.org/#!/diyan/pywinrm
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  # Build/test dependencies
  - sudo apt-get install libffi-dev
  - pip install cffi
  - pip install -r requirements.txt --use-mirrors
  # TODO Wrap explicit environment setup into following:
  #- python setup.py install
script: nosetests -v
# TODO wrap unit test execution into following:
# python setup.py test
