# http://travis-ci.org/#!/diyan/pywinrm
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - pip install -r requirements.txt --use-mirrors --upgrade
  - pip install coveralls --use-mirrors --upgrade
script:
  #TODO enable pep8 checking
  #py.test -v --pep8 winrm --cov winrm --cov-report term-missing winrm/tests/
  - py.test -v --cov winrm --cov-report term-missing winrm/tests/
after_success:
  - coveralls
