# http://travis-ci.org/#!/diyan/pywinrm
language: python
python:
  - 2.6
  - 2.7
  # py 3.2 removed since pytest itself is broken there
  - 3.3
  - 3.4
  - 3.5
  - pypy
install:
  #- sudo apt-get install libffi-dev
  #- pip install cffi coveralls
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - py.test -v --pep8 --cov=winrm --cov-report=term-missing winrm/tests/

after_success:
  - coveralls
